import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';
import QueryProvider from '../components/QueryProvider';
import { Toaster } from '@/components/ui/sonner';

const nunitoFont = Nunito({
  variable: '--font-family-nunito',
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Project 2',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(nunitoFont.variable, `antialiased`)}>
        <QueryProvider>{children}</QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
